spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hongbo-code/config-repo
          username: 59234466@qq.com
          password: HONGBO890504
          basedir: C:\Users\hongbo\Desktop\config-repoi
  rabbitmq:
    host: 192.168.1.8
    port: 5672
    username: user
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
